# Generated by Django 4.2.24 on 2025-09-24 21:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_category_image_article_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingnews',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
