# Generated by Django 4.2.24 on 2025-09-22 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Models'},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='start_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
